// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: auth.proto

package authapp

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for generating a token.
type CreateTokenRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_UserName    *string                `protobuf:"bytes,2,opt,name=user_name,json=userName"`
	xxx_hidden_Admin       bool                   `protobuf:"varint,3,opt,name=admin"`
	xxx_hidden_Duration    *string                `protobuf:"bytes,4,opt,name=duration"`
	xxx_hidden_Endpoints   []string               `protobuf:"bytes,5,rep,name=endpoints"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateTokenRequest) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *CreateTokenRequest) GetUserName() string {
	if x != nil {
		if x.xxx_hidden_UserName != nil {
			return *x.xxx_hidden_UserName
		}
		return ""
	}
	return ""
}

func (x *CreateTokenRequest) GetAdmin() bool {
	if x != nil {
		return x.xxx_hidden_Admin
	}
	return false
}

func (x *CreateTokenRequest) GetDuration() string {
	if x != nil {
		if x.xxx_hidden_Duration != nil {
			return *x.xxx_hidden_Duration
		}
		return ""
	}
	return ""
}

func (x *CreateTokenRequest) GetEndpoints() []string {
	if x != nil {
		return x.xxx_hidden_Endpoints
	}
	return nil
}

func (x *CreateTokenRequest) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *CreateTokenRequest) SetUserName(v string) {
	x.xxx_hidden_UserName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *CreateTokenRequest) SetAdmin(v bool) {
	x.xxx_hidden_Admin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *CreateTokenRequest) SetDuration(v string) {
	x.xxx_hidden_Duration = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CreateTokenRequest) SetEndpoints(v []string) {
	x.xxx_hidden_Endpoints = v
}

func (x *CreateTokenRequest) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateTokenRequest) HasUserName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateTokenRequest) HasAdmin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateTokenRequest) HasDuration() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CreateTokenRequest) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *CreateTokenRequest) ClearUserName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UserName = nil
}

func (x *CreateTokenRequest) ClearAdmin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Admin = false
}

func (x *CreateTokenRequest) ClearDuration() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Duration = nil
}

type CreateTokenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token     *string
	UserName  *string
	Admin     *bool
	Duration  *string
	Endpoints []string
}

func (b0 CreateTokenRequest_builder) Build() *CreateTokenRequest {
	m0 := &CreateTokenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Token = b.Token
	}
	if b.UserName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_UserName = b.UserName
	}
	if b.Admin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Admin = *b.Admin
	}
	if b.Duration != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Duration = b.Duration
	}
	x.xxx_hidden_Endpoints = b.Endpoints
	return m0
}

// Response message for token generation.
type CreateTokenResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateTokenResponse) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *CreateTokenResponse) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CreateTokenResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateTokenResponse) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

type CreateTokenResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token *string
}

func (b0 CreateTokenResponse_builder) Build() *CreateTokenResponse {
	m0 := &CreateTokenResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Token = b.Token
	}
	return m0
}

// Request message for authentication.
type AuthenticateRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_Admin       bool                   `protobuf:"varint,2,opt,name=admin"`
	xxx_hidden_Endpoint    *string                `protobuf:"bytes,3,opt,name=endpoint"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthenticateRequest) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *AuthenticateRequest) GetAdmin() bool {
	if x != nil {
		return x.xxx_hidden_Admin
	}
	return false
}

func (x *AuthenticateRequest) GetEndpoint() string {
	if x != nil {
		if x.xxx_hidden_Endpoint != nil {
			return *x.xxx_hidden_Endpoint
		}
		return ""
	}
	return ""
}

func (x *AuthenticateRequest) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AuthenticateRequest) SetAdmin(v bool) {
	x.xxx_hidden_Admin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AuthenticateRequest) SetEndpoint(v string) {
	x.xxx_hidden_Endpoint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AuthenticateRequest) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthenticateRequest) HasAdmin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthenticateRequest) HasEndpoint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuthenticateRequest) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *AuthenticateRequest) ClearAdmin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Admin = false
}

func (x *AuthenticateRequest) ClearEndpoint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Endpoint = nil
}

type AuthenticateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token    *string
	Admin    *bool
	Endpoint *string
}

func (b0 AuthenticateRequest_builder) Build() *AuthenticateRequest {
	m0 := &AuthenticateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Token = b.Token
	}
	if b.Admin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Admin = *b.Admin
	}
	if b.Endpoint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Endpoint = b.Endpoint
	}
	return m0
}

// Response message for authentication.
type AuthenticateResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TokenId     *string                `protobuf:"bytes,1,opt,name=token_id,json=tokenId"`
	xxx_hidden_Subject     *string                `protobuf:"bytes,2,opt,name=subject"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthenticateResponse) GetTokenId() string {
	if x != nil {
		if x.xxx_hidden_TokenId != nil {
			return *x.xxx_hidden_TokenId
		}
		return ""
	}
	return ""
}

func (x *AuthenticateResponse) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *AuthenticateResponse) SetTokenId(v string) {
	x.xxx_hidden_TokenId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AuthenticateResponse) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AuthenticateResponse) HasTokenId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AuthenticateResponse) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthenticateResponse) ClearTokenId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TokenId = nil
}

func (x *AuthenticateResponse) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Subject = nil
}

type AuthenticateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TokenId *string
	Subject *string
}

func (b0 AuthenticateResponse_builder) Build() *AuthenticateResponse {
	m0 := &AuthenticateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TokenId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_TokenId = b.TokenId
	}
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Subject = b.Subject
	}
	return m0
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"\x97\x01\n" +
	"\x12CreateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x14\n" +
	"\x05admin\x18\x03 \x01(\bR\x05admin\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\x12\x1c\n" +
	"\tendpoints\x18\x05 \x03(\tR\tendpoints\"+\n" +
	"\x13CreateTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"]\n" +
	"\x13AuthenticateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05admin\x18\x02 \x01(\bR\x05admin\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"K\n" +
	"\x14AuthenticateResponse\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject2\x91\x01\n" +
	"\x04Auth\x12B\n" +
	"\vCreateToken\x12\x18.auth.CreateTokenRequest\x1a\x19.auth.CreateTokenResponse\x12E\n" +
	"\fAuthenticate\x12\x19.auth.AuthenticateRequest\x1a\x1a.auth.AuthenticateResponseB3Z1github.com/ardanlabs/kronk/app/domain/grpcauthappb\beditionsp\xe9\a"

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_proto_goTypes = []any{
	(*CreateTokenRequest)(nil),   // 0: auth.CreateTokenRequest
	(*CreateTokenResponse)(nil),  // 1: auth.CreateTokenResponse
	(*AuthenticateRequest)(nil),  // 2: auth.AuthenticateRequest
	(*AuthenticateResponse)(nil), // 3: auth.AuthenticateResponse
}
var file_auth_proto_depIdxs = []int32{
	0, // 0: auth.Auth.CreateToken:input_type -> auth.CreateTokenRequest
	2, // 1: auth.Auth.Authenticate:input_type -> auth.AuthenticateRequest
	1, // 2: auth.Auth.CreateToken:output_type -> auth.CreateTokenResponse
	3, // 3: auth.Auth.Authenticate:output_type -> auth.AuthenticateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
