schema = 3

[mod]
  [mod."cel.dev/expr"]
    version = "v0.25.3"
    hash = "sha256-W17jP8I+4zsPEUMahiOp94WxihvZVnbmGTofF+LL9C8="
  [mod."cloud.google.com/go"]
    version = "v0.123.0"
    hash = "sha256-OjuvlqYrGvoUiXO/5ALbMxHvXRlrhDjLby1BN/nuhAw="
  [mod."cloud.google.com/go/auth"]
    version = "v0.23.2"
    hash = "sha256-D28j2x5WFAg56/zTI9jGTH9MDUhteBo/RP1OKRKjB3s="
  [mod."cloud.google.com/go/auth/oauth2adapt"]
    version = "v0.2.8"
    hash = "sha256-GoXFqAbp1WO1tDj07PF5EyxDYvCBP0l0qwxY2oV2hfc="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.9.0"
    hash = "sha256-VFqQwLJKyH1zReR/XtygEHP5UkI01T9BHEL0hvXtauo="
  [mod."cloud.google.com/go/iam"]
    version = "v1.13.0"
    hash = "sha256-lHnccB5IfkM/B1K0V+T/J1mBMXU84iyE/FsfnDk4Gzc="
  [mod."cloud.google.com/go/monitoring"]
    version = "v1.30.0"
    hash = "sha256-AOxUKDkE75OQV1Jp43Nh8mgAu/SzvNKjzt1+R7Nb/HM="
  [mod."cloud.google.com/go/storage"]
    version = "v1.67.0"
    hash = "sha256-NmVw49YjRfaqioVzQj7RmWj9hOPlNxtPmFdv0yCOeqc="
  [mod."github.com/GoogleCloudPlatform/opentelemetry-operations-go/detectors/gcp"]
    version = "v1.37.0"
    hash = "sha256-Zng5YdYZvLZE45BHWMn+0i6hbq/pgUeCnzpndQnmWgI="
  [mod."github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric"]
    version = "v0.61.0"
    hash = "sha256-uRiNTk+pdUtXNrrshlTzejclwea6cuk+E47dxsUR57k="
  [mod."github.com/GoogleCloudPlatform/opentelemetry-operations-go/internal/resourcemapping"]
    version = "v0.61.0"
    hash = "sha256-nWBR/1zx3mWveInxTUpV81MCAN81P4O700jzQ2/Z4mk="
  [mod."github.com/agnivade/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-3XnCzf7tFgEE0MmjxvjfWaw6qK6mKLabFZ3c23JIH9Y="
  [mod."github.com/ardanlabs/bucky"]
    version = "v1.1.2"
    hash = "sha256-kiHQ40QaMufu7vMMuMbu62brPsTqw0EF6iPZ3f6jbh4="
  [mod."github.com/ardanlabs/conf/v3"]
    version = "v3.13.0"
    hash = "sha256-WlPMHIHqJJVpe1tryI8si4jknRZr484+z0F/7ojYimw="
  [mod."github.com/ardanlabs/jinja"]
    version = "v1.6.0"
    hash = "sha256-xK0llBUpxqQXLdFCs/WRBSJSLjYQbqDj1cvOWCioxdc="
  [mod."github.com/ardanlabs/malina"]
    version = "v1.0.8"
    hash = "sha256-zu4R/Gy659WLpAgi5XROqS4sxnIzz5aOs30GPD9Kz6E="
  [mod."github.com/arl/statsviz"]
    version = "v0.8.2"
    hash = "sha256-8KmSQolXTl2aBo9bY8/dmby82ItHVHiYLRu/UNGRF8Q="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.46.0"
    hash = "sha256-ygPR1IbZiv1p3DTKAB2ZVVQcvX6EGwUedGk2Jc5PXII="
  [mod."github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream"]
    version = "v1.7.20"
    hash = "sha256-ICB2yD83Gl628LRkg3HhYlDtsL4xgGhOmphZ5D0bJXI="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.33.3"
    hash = "sha256-Ai4hgN/jjLmHvMKfkZcW5+4FIe/6Voja1tFKuXKA8hc="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.20.3"
    hash = "sha256-XPg+tT3RnnBEhMOIeHhEH3Lr0U8tfAtR27d+idbaCYU="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.19.2"
    hash = "sha256-rBu9gzIcgMPw6h6QnAxzzgTwEevrsy+qxEBI8NAMMx4="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.5.2"
    hash = "sha256-/r9+bi8QJPgiGNxB12VnXAJiPUhPxy7Fgr6qspmKT0E="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.8.2"
    hash = "sha256-/dlIHHhMS3FsLDintHCXjxbI5/FvDd6/EOdHquOjFBY="
  [mod."github.com/aws/aws-sdk-go-v2/internal/v4a"]
    version = "v1.5.2"
    hash = "sha256-uoo56Z2Y3rXF0IMO/9so5m2OBd1ugMFuM3Vo9u5lcPU="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.13.19"
    hash = "sha256-LfifyqFh49PPH0asF1TJz3QJYHTwxQttthUD5p4z2YM="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/checksum"]
    version = "v1.11.2"
    hash = "sha256-MQwQqM+X8T93iSkt8NT9hXNd8YaXtrPQVTwlvovmgV4="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.14.2"
    hash = "sha256-LN9CZLgdVTGk7Ym5KLexE9ghcEHs0HqAv54EapYG/+Y="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/s3shared"]
    version = "v1.20.2"
    hash = "sha256-V8ePq6lKDmUsinL8R9nWkf+b3KW0mJ3vz9AUbkq1m1U="
  [mod."github.com/aws/aws-sdk-go-v2/service/s3"]
    version = "v1.111.0"
    hash = "sha256-YvIP0wcKEJwDxAL6vuDUoix6ka5oaCTYKYX5SM0dcEQ="
  [mod."github.com/aws/aws-sdk-go-v2/service/signin"]
    version = "v1.9.0"
    hash = "sha256-jG/Z5ihIKmCsCPfL8ER1MYUh9HBQgVqcy5HLECJlug4="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.37.0"
    hash = "sha256-h14CY5x3s5gjfoQoVJws/+Og/wAKVx005ywvc40dQAU="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.42.0"
    hash = "sha256-6cbzv7hq0LoBqKgIASNndiztnHLwHpS3VEvRiyKVQ5c="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.49.0"
    hash = "sha256-MXKpCmLUlTZ1E8ExG9sz8E+Zk5UIHsZNvEgBKKAZE4E="
  [mod."github.com/aws/smithy-go"]
    version = "v1.28.1"
    hash = "sha256-52wJGnuZVxhZtqgp4Gf7mgYrK6DOL8hFgtjo8e1NlCA="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bgentry/go-netrc"]
    version = "v0.0.0-20140422174119-9fd32a8b3d3d"
    hash = "sha256-NDxQzO5C5M/aDz5/pjUHfZUh4VwIXovbb3irtxWCwjY="
  [mod."github.com/cenkalti/backoff/v5"]
    version = "v5.0.3"
    hash = "sha256-bKq43PPD8RM6e7HePxHaO27traqm76bkvHcTVTQ+jeY="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/cncf/xds/go"]
    version = "v0.0.0-20260202195803-dba9d589def2"
    hash = "sha256-nCcna5Dwr8a+FgdSZt43VmoMds5U0FZta2vpJfdMOhs="
  [mod."github.com/decred/dcrd/dcrec/secp256k1/v4"]
    version = "v4.4.1"
    hash = "sha256-FfHNUmNdqtxHP5OFxqlJJ5jiZ9unpjeLGJS2yHoaNfU="
  [mod."github.com/dgraph-io/badger/v4"]
    version = "v4.9.6"
    hash = "sha256-oZrhYpOMRydX9YFU/g9yH9qiRBUcxfDECHjehD2WzaU="
  [mod."github.com/dgraph-io/ristretto/v2"]
    version = "v2.4.2"
    hash = "sha256-AshHZwJ5ZalwUrGxlff2b0VwVLsjrIft31gve+CnsMI="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/ebitengine/purego"]
    version = "v0.11.0"
    hash = "sha256-JjleZ8TbDFCUrV2whfa/utBtz/xnGiLx3LcC+VemN2U="
  [mod."github.com/envoyproxy/go-control-plane/envoy"]
    version = "v1.39.0"
    hash = "sha256-EjlqubUTPeOSGsIxn+2VcjHAZqbZTTESxUaIzRkPby4="
  [mod."github.com/envoyproxy/protoc-gen-validate"]
    version = "v1.3.3"
    hash = "sha256-NsI6A4CBVTpAq4gsmv66sMx0gvY0J0kF/t9zbtlRLr4="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.1.0"
    hash = "sha256-oePAjhI+dYRrMQAeUWnJ3o+PdHFU1tk1Z/R3/kGdjnw="
  [mod."github.com/go-jose/go-jose/v4"]
    version = "v4.1.5"
    hash = "sha256-GnRt1sMlr4qn9yJ3RCtZSezN+C9DXR+v5smzAKmi26M="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.4"
    hash = "sha256-q9HX9aelONTLsywyLY4Wc5UYCK+wG0FbSzFWisCYiIA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/gobwas/glob"]
    version = "v0.2.3"
    hash = "sha256-hYHMUdwxVkMOjSKjR7UWO0D0juHdI4wL8JEy5plu/Jc="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.6"
    hash = "sha256-/REW1EDZ3Ta45hrDNR9YTIlhkxQQI8OeK5TxBNJ47Ho="
  [mod."github.com/golang-jwt/jwt/v5"]
    version = "v5.3.1"
    hash = "sha256-h7AszH+3YWL3IV0+miY9vbtU0gM/2RpuASSGAYAgWcA="
  [mod."github.com/google/flatbuffers"]
    version = "v25.12.19+incompatible"
    hash = "sha256-NOYL9CWJgjdY1u4j/Ccyz2i50RjvZfNm/K+EFj7GIYk="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/jsonschema-go"]
    version = "v0.4.3"
    hash = "sha256-AJDx6ZY91bQV0/mPHGDwko7+FgH/ihCH0kHubcbJIU4="
  [mod."github.com/google/s2a-go"]
    version = "v0.1.9"
    hash = "sha256-0AdSpSTso4bATmM/9qamWzKrVtOLDf7afvDhoiT/UpA="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/googleapis/enterprise-certificate-proxy"]
    version = "v0.3.21"
    hash = "sha256-h8t4jzU7hRY/KaSI51xAkxX2934i5k6XVvpuNPef4iE="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.24.1"
    hash = "sha256-BNwMNzdEpE8UEzIn4F+fPGrCsHDTyJBU2RQOumy4uM0="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.30.0"
    hash = "sha256-SKvojuMn48wxg9Dd8D0BcS4PZO3OHIFOJEMYlpvgLsk="
  [mod."github.com/hajimehoshi/go-mp3"]
    version = "v0.3.4"
    hash = "sha256-h6l0PuIS0h1zdB8MEqHTTgg8dE6nL6PSOt583ymaPnA="
  [mod."github.com/hashicorp/aws-sdk-go-base/v2"]
    version = "v2.0.0-beta.74"
    hash = "sha256-qK601AfHDPzL8de88/1/JvqCvaQgHSWjpN++sc+mmcM="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-getter"]
    version = "v1.8.9"
    hash = "sha256-Non3LDJ8LXWAxeQQN2PmMGaRQjnQ56KVzudx2X0jH08="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.9.0"
    hash = "sha256-sRr/50k8Wra0PJLCJgSkIxvR+ce3PItx4HpFvVijGYk="
  [mod."github.com/hybridgroup/yzma"]
    version = "v1.26.0"
    hash = "sha256-vgxO4QjlNtdMiRBhs/FaR0WHDlFaBfFkhsPynNVBD20="
  [mod."github.com/icza/bitio"]
    version = "v1.1.0"
    hash = "sha256-CtV/dr1L46cZ65EnK9DrBduZCaMnTGf4N2MnElCymtM="
  [mod."github.com/icza/mjpeg"]
    version = "v0.0.0-20230330134156-38318e5ab8f4"
    hash = "sha256-c5bC4+8LV6GvstV+1qZJxKrDE7fmWyjKCK8jo9Mz1J0="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jupiterrider/ffi"]
    version = "v0.7.0"
    hash = "sha256-9LUC4rq2yFmGar4HmYNjHB+WYfMLCOh2W4pMJjCrlw0="
  [mod."github.com/klauspost/compress"]
    version = "v1.20.0"
    hash = "sha256-M7FmkBv1S66kAjg9yjkzY/PtCb/RTsRABSDLYYQ9itM="
  [mod."github.com/lestrrat-go/blackmagic"]
    version = "v1.0.4"
    hash = "sha256-HmWOpwoPDNMwLdOi7onNn3Sb+ZsAa3Ai3gVBbXmQ0e8="
  [mod."github.com/lestrrat-go/dsig"]
    version = "v1.4.0"
    hash = "sha256-ViVzW17736GKucPd3SA7oUvE2Oprx4ma+27EnpXpOys="
  [mod."github.com/lestrrat-go/dsig-secp256k1"]
    version = "v1.0.0"
    hash = "sha256-kKdirGAHjx0lZPGPJCsvRVqPGTlFUGcF1SIvtXkUJRo="
  [mod."github.com/lestrrat-go/httpcc"]
    version = "v1.0.1"
    hash = "sha256-SMRSwJpqDIs/xL0l2e8vP0W65qtCHX2wigcOeqPJmos="
  [mod."github.com/lestrrat-go/httprc/v3"]
    version = "v3.0.6"
    hash = "sha256-gmHPNPCPq/Vn4s1PBYoSqlNaPNmXsnNTef9nL+6K+3M="
  [mod."github.com/lestrrat-go/jwx/v3"]
    version = "v3.2.0"
    hash = "sha256-+zd5Dhz6HC/UXPSZCAUEo5I+c8xaEJjFF+l2OtYzqJw="
  [mod."github.com/lestrrat-go/option/v2"]
    version = "v2.0.0"
    hash = "sha256-ZmegDY7E3+tLd+kkNal1aeq3nfNH/dlWPpXOJfI3L5Q="
  [mod."github.com/maypok86/otter/v2"]
    version = "v2.3.0"
    hash = "sha256-ELzmi/s2WqDeUmzSGnfx+ys2Hs28XHqF7vlEzyRotIA="
  [mod."github.com/mewkiz/flac"]
    version = "v1.0.14"
    hash = "sha256-w5erJZMFlfDD5KIcyAm5W8gLEqV0ufM5eJh16WjdAe0="
  [mod."github.com/mewkiz/pkg"]
    version = "v0.0.0-20260703220044-4fb89b18cc87"
    hash = "sha256-oUWARz9PjGl+MZevoP/MN291B5lRMShOhj2qFIpfhz8="
  [mod."github.com/mewpkg/term"]
    version = "v0.0.0-20241026122259-37a80af23985"
    hash = "sha256-WgvLJUMIXdYgpZivX38fZqaMTIimnpLdpRVsBhjEWZI="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/modelcontextprotocol/go-sdk"]
    version = "v1.7.0"
    hash = "sha256-+XbqHCwhQ8nDq3qheb50FanzJJToWVfcv4tDSf2u2Kc="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/open-policy-agent/opa"]
    version = "v1.20.2"
    hash = "sha256-gU0q7N8Zda5y94054C0E9jg65HpJ9C0Sd6rbWodtcoY="
  [mod."github.com/planetscale/vtprotobuf"]
    version = "v0.6.1-0.20240319094008-0393e58bdf10"
    hash = "sha256-L8dyNm+PCRDNADiIGKZqsPkCgB4xpLrosZjssrN+sUY="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.24.1"
    hash = "sha256-HAOFVYyPiU7hVS1XXMMjkbGgTT7/UN0zVHXYOnjr7is="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.3"
    hash = "sha256-uYXpFkXMT4AXWJShrCRnu51vhGQAuAU3LFQhhGVJ+74="
  [mod."github.com/prometheus/common"]
    version = "v0.71.0"
    hash = "sha256-94kki7QNQjmL5UFgJfqN5qeLC/dCqMEevxCHHKyMqUk="
  [mod."github.com/prometheus/procfs"]
    version = "v0.22.0"
    hash = "sha256-TRwVHKgW4NnPuC6Me38OD57ccM8AfnS7IxtcAx2TAH4="
  [mod."github.com/rcrowley/go-metrics"]
    version = "v0.0.0-20250401214520-65e299d6c5c9"
    hash = "sha256-xTuRRrDpI/ANi/cvRMerx+gHP/ePGT0MxHHB5UXMVus="
  [mod."github.com/segmentio/asm"]
    version = "v1.2.1"
    hash = "sha256-XhAJObkSa7gjx3PqYrreVEcMHBc/rDVeY/lWvNccGB0="
  [mod."github.com/segmentio/encoding"]
    version = "v0.5.4"
    hash = "sha256-AVIwCIh/L7X7CaGGX2gYOlurO/xifjjLpK+AIRTv2rQ="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.10.2"
    hash = "sha256-1BKin1NpY1kFawnHkY0FxQ152aeB82RRKIDWJLctZB4="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/spiffe/go-spiffe/v2"]
    version = "v2.8.1"
    hash = "sha256-9rVvr5oguOnMBZYFv06cg/DuOUNxKAD+qO/Y85AXf0g="
  [mod."github.com/stretchr/testify"]
    version = "v1.12.1"
    hash = "sha256-9MTDdVjZMh1MJ5EH3HmAFrm24YqZayeMBgKwtaURZCc="
  [mod."github.com/tchap/go-patricia/v2"]
    version = "v2.3.3"
    hash = "sha256-6Ahy1QFyx3T0z5zghIGWBgfagdRGPLgrKYYcYvJj2ig="
  [mod."github.com/ulikunitz/xz"]
    version = "v0.5.16"
    hash = "sha256-H9PHsg4f6p+8MGGddvO8qGY17aXu4uHch+0zgsw6dlo="
  [mod."github.com/valyala/fastjson"]
    version = "v1.6.10"
    hash = "sha256-D2lL4FnkeL/eRLiRW6ihhqQkzEqHVvhbEvZoYTVNmbU="
  [mod."github.com/vektah/gqlparser/v2"]
    version = "v2.5.37"
    hash = "sha256-mH2WN/2OjnNb+w1eufpcZ+xBAn5oR8KR73yzBAV5s+s="
  [mod."github.com/xeipuuv/gojsonpointer"]
    version = "v0.0.0-20190905194746-02993c407bfb"
    hash = "sha256-/u+qznDY8cnECZYIgSMRpKVWs04yAkW6EoGhqt+t73g="
  [mod."github.com/xeipuuv/gojsonreference"]
    version = "v0.0.0-20180127040603-bd5ef7bd5415"
    hash = "sha256-ZbXA+ASQrTgBQzasUKC9vznrOGpquYyWr+uwpm46fvU="
  [mod."github.com/yashtewari/glob-intersection"]
    version = "v0.2.0"
    hash = "sha256-SwTh5MEtGTqytNqlvoMWaEpVx9iABnnBJ6FzLJ5qg+s="
  [mod."github.com/yosida95/uritemplate/v3"]
    version = "v3.0.2"
    hash = "sha256-znUsCrfogPwAUNsdxBL93jIW/joercUm7RxKSExuWTM="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.2.1"
    hash = "sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE="
  [mod."go.opentelemetry.io/contrib/detectors/gcp"]
    version = "v1.46.0"
    hash = "sha256-oSUGEdiG9j2kN3gf0X1r+zFcAJfNuqMu2wS8LwtDvFI="
  [mod."go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"]
    version = "v0.71.0"
    hash = "sha256-2vwtDspRM7jZyvxclBmKTCDZ31qw/TiG+HHI6Z8ub2s="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.71.0"
    hash = "sha256-E5YtRLrs1/LqpvPt6LzC+sDpmxSROgpNmgca5s6iyCg="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.46.0"
    hash = "sha256-2+xTacXn22hsJuMGGgXwazMbP/ZW5gkPRnf+rNUZgvQ="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.46.0"
    hash = "sha256-dhQCMAwny2CrgH3iJfTW0r0klpi7os0nht3zdLeWL6E="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.46.0"
    hash = "sha256-qIv7G8ADgdnitDv9+jQUYBARM6zUtt9kBX5NCNKbB40="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.46.0"
    hash = "sha256-cY1DXXzRfcP0kKh7oBzowbu6kbFr3jANiEVyMlD5Bt8="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.46.0"
    hash = "sha256-bDS4r1NfK2jZmTx5KUcrPJpPC2Men1lOuEKhy3vkMxc="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.46.0"
    hash = "sha256-7HyWcBj0lBc9V29f14gPFS3mBPrHZmC3TFuRsfIo7mI="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.46.0"
    hash = "sha256-zfj85gCR5Z3v1N+8nlOO+6+FVShaL/7Vb/3lXjdXnnw="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.11.0"
    hash = "sha256-jBcVUiab9mWgLmPsrCYK7sC2j15AJ47QJM4prnqGGkE="
  [mod."go.yaml.in/yaml/v2"]
    version = "v2.4.4"
    hash = "sha256-ecT2ZXw7iT+63J4210xA6sMz0fUFXmDzLwZe2FzaNFU="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.5"
    hash = "sha256-ygho+GU5kE7vPMx+dZYyNfCaeMjNxj66XmrcVf3afFE="
  [mod."golang.org/x/crypto"]
    version = "v0.56.0"
    hash = "sha256-B4el+S5mIq9f5uvCjMQ4Fh3EAxxo7Cb0yeXoxJXuyF8="
  [mod."golang.org/x/image"]
    version = "v0.45.0"
    hash = "sha256-oI6UVl+gAcEpXHFszh8P8WvOZ6Ob41982Op9/CBwyjs="
  [mod."golang.org/x/net"]
    version = "v0.58.0"
    hash = "sha256-fDOkQJXURrbq2dBGa91bCUsXknCZlo3ru2JIofSOGRo="
  [mod."golang.org/x/oauth2"]
    version = "v0.36.0"
    hash = "sha256-evS7WkMrpgonmTcqtWFpC5rSKZN8O+vnAhNUs1MS9kw="
  [mod."golang.org/x/sync"]
    version = "v0.22.0"
    hash = "sha256-VZjl0fAM0p/nI81zh+pdBjzxFupx0UcKYXBBpL2ZS7k="
  [mod."golang.org/x/sys"]
    version = "v0.47.0"
    hash = "sha256-TpbRyWWqHjddP6QzUgAbaLd2EE0S+GYNRUIDJd18r98="
  [mod."golang.org/x/text"]
    version = "v0.41.0"
    hash = "sha256-22nHcolG87qSPahT2Ey8S5iGlCLAglE9ObYXO6XZ3ZY="
  [mod."golang.org/x/time"]
    version = "v0.15.0"
    hash = "sha256-5D24A65wn7k93Jj3+918UKjB9ccmGHPBEqjD2XDB92E="
  [mod."google.golang.org/api"]
    version = "v0.297.0"
    hash = "sha256-2xvIgAA44TkUlztwYsUz8AmG87Xlcr/w78G7RFimiuk="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20260904194346-d0f1323225a4"
    hash = "sha256-LupLjs7uYQ2JQCN++trpMaWRXDqHFZtlnEPphpc8hVw="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20260904194346-d0f1323225a4"
    hash = "sha256-NdWeSHN01GD0hGfHtIgXxyTSU3ZANLE286wmOnTM6ZI="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20260904194346-d0f1323225a4"
    hash = "sha256-CQdjYGIrgAnEDfWW3DIJF9Orf7oJdhx3G9rGg6fow88="
  [mod."google.golang.org/grpc"]
    version = "v1.83.2"
    hash = "sha256-q5VtdeJvWM7kbIvui8ncNV/+Rm+d0y/b6XkNN0/u1is="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.12"
    hash = "sha256-MKd0AdkWEe2A79mGPzOY5I76nMqTsGJKQNPJOKyOwkQ="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.6.0"
    hash = "sha256-49hg7IVPzwxeovp+HTMiWa/10NMMTSTjAdCmIv6p9dw="
